#!/bin/bash

TIPS_STATUS=$(cat $HOME/.config/eww/sysmenu/scripts/tips/tips-lock)

if [[ $TIPS_STATUS == "on" ]]; then
    eww open-many --toggle background-closer sysmenu tips
else 
    eww open-many --toggle background-closer sysmenu
fi
